In [15]:
import numpy as np
from math import inf

In [2]:
arr = np.array([11, 22, 33, 44, 55, 66])

In [3]:
arr.shape

(6,)

In [4]:
arr.reshape(3,2)[:2,:]

array([[11, 22],
       [33, 44]])

In [5]:
arr.reshape(3,2)[2:,:]

array([[55, 66]])

In [6]:
arr.reshape(3,2,1)

array([[[11],
        [22]],

       [[33],
        [44]],

       [[55],
        [66]]])

In [8]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])

In [10]:
print(a*b)
print(a.dot(b))

[1 4 9]
14


In [12]:
from numpy.linalg import norm
norm(a,1)

6.0

In [14]:
norm(a)

3.7416573867739413

In [16]:
norm(a, inf)

3.0

In [17]:
a=np.array(([
  [1, 2],
  [3, 4],
  [5, 6]]))
b= np.array([
[1, 2],
[3, 4]])

In [18]:
a.dot(b)

array([[ 7, 10],
       [15, 22],
       [23, 34]])

In [19]:
m=np.array([
  [1, 2, 3],
  [1, 2, 3],
  [1, 2, 3]])

In [21]:
np.tril(m)

array([[1, 0, 0],
       [1, 2, 0],
       [1, 2, 3]])

In [22]:
np.triu(m)

array([[1, 2, 3],
       [0, 2, 3],
       [0, 0, 3]])

In [23]:
np.diag(m)

array([1, 2, 3])

In [29]:
from numpy.linalg import inv
q = np.array([
[1, 0],
[0, -1]])
V= inv(q)
print(q)
print(q.T)
print(V)
print(q .dot(q.T))

[[ 1  0]
 [ 0 -1]]
[[ 1  0]
 [ 0 -1]]
[[ 1.  0.]
 [-0. -1.]]
[[1 0]
 [0 1]]


In [30]:
from numpy import array
from numpy.linalg import matrix_rank # rank
v1 = array([1,2,3])
print(v1)
vr1 = matrix_rank(v1)
print(vr1)
# zero rank
v2 = array([0,0,0,0,0])
print(v2)
vr2 = matrix_rank(v2)
print(vr2)

[1 2 3]
1
[0 0 0 0 0]
0


In [31]:
from numpy import array
from numpy.linalg import det # define matrix
A = array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]])
print(A)
# calculate determinant
B = det(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
0.0


In [38]:
from numpy import array, count_nonzero
from scipy.sparse import csr_matrix # create dense matrix
A = array([
  [1, 0, 0, 1, 0, 0],
  [0, 0, 2, 0, 0, 1],
  [0, 0, 0, 2, 0, 0]])
# convert to sparse matrix (CSR method) 
S = csr_matrix(A)
print(S)

  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2


In [36]:
# reconstruct dense matrix
B = S.todense()
print(B)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


In [39]:
sparsity = 1.0 - count_nonzero(A) / A.size 
print(sparsity)

0.7222222222222222


In [40]:
from numpy import array
T = array([
[[1,2,3], [4,5,6], [7,8,9]], [[11,12,13], [14,15,16], [17,18,19]], [[21,22,23], [24,25,26], [27,28,29]]])
print(T.shape) 
print(T)

(3, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


In [45]:
from numpy import array 
from scipy.linalg import lu 
A = array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]])

P, L, U = lu(A)

print(L.dot(U))
print(P)

[[7. 8. 9.]
 [1. 2. 3.]
 [4. 5. 6.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [50]:
from numpy import array
from numpy.linalg import eig # define matrix
A = array([
  [1, 2, 3],
  [4, 5, 6],
   [7, 8, 9]])
# factorize
values, vectors = eig(A)
print(values)
print(vectors)

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
[ 13.88315603  58.88315603 103.88315603]


In [58]:
A.dot(vectors[:,0])

array([ -3.73863537,  -8.46653421, -13.19443305])

In [56]:
vectors[:,0] * values[0]

array([ -3.73863537,  -8.46653421, -13.19443305])

In [62]:
from numpy import diag
from numpy.linalg import inv
Q = vectors
# create inverse of eigenvectors matrix
R = inv(Q)
# create diagonal matrix from eigenvalues 
L = diag(values)
# reconstruct the original matrix
B = Q.dot(L).dot(R)
print(B)

[[ 0.17757009  1.88785047  3.59813084]
 [ 1.88785047  4.43925234  6.99065421]
 [ 3.59813084  6.99065421 10.38317757]]
