In [1]:
import torch

In [2]:
t1 = torch.tensor(4.)
print(t1.shape)
print(t1)

torch.Size([])
tensor(4.)


In [3]:
t1 = torch.tensor([1., 2, 3, 4])
print(t1.shape)
print(t1)

torch.Size([4])
tensor([1., 2., 3., 4.])


In [4]:
t1 = torch.tensor([[5., 6], 
                   [7, 8], 
                   [9, 10]])
print(t1.shape)
print(t1)

torch.Size([3, 2])
tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


In [5]:
t1 =  torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])
print(t1.shape)
print(t1)

torch.Size([2, 2, 3])
tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


In [6]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [7]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [8]:
y.backward()

In [9]:
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)
