In [1]:
import numpy as np
weights = np.array([0.5,0.48,-0.7])
alpha = 0.1

streetlights = np.array( [ [ 1, 0, 1 ],
                           [ 0, 1, 1 ],
                           [ 0, 0, 1 ],
                           [ 1, 1, 1 ],
                           [ 0, 1, 1 ],
                           [ 1, 0, 1 ] ] )

walk_vs_stop = np.array( [ 0, 1, 0, 1, 1, 0 ] )


In [2]:
input = streetlights[0] # [1,0,1]
goal_prediction = walk_vs_stop[0] # equals 0... i.e. "stop"

for iteration in range(40):
    error_for_all_lights = 0
    for row_index in range(len(walk_vs_stop)):
        input = streetlights[row_index]
        prediction = input.dot(weights)
        error = (goal_prediction - prediction) ** 2
        delta = prediction - goal_prediction
        weights = weights - (alpha * (input * delta))
        error_for_all_lights += error	
        print("Prediction:" + str(prediction))
    print("Error:" + str(error_for_all_lights))

Prediction:-0.19999999999999996
Prediction:-0.19999999999999996
Prediction:-0.6599999999999999
Prediction:0.42600000000000005
Prediction:-0.17919999999999997
Prediction:-0.1412799999999999
Error:0.7491486783999998
Prediction:-0.1130239999999999
Prediction:-0.11792959999999986
Prediction:-0.5814566399999999
Prediction:0.46663238399999996
Prediction:-0.1295244927999999
Prediction:-0.10085460351999997
Error:0.6094676664160464
Prediction:-0.08068368281600002
Prediction:-0.08546576560640001
Prediction:-0.53032135992576
Prediction:0.4589805137410559
Prediction:-0.1071365792407552
Prediction:-0.08405067852371972
Error:0.5242608737226604
Prediction:-0.06724054281897579
Prediction:-0.07058014125833462
Prediction:-0.4902864811231111
Prediction:0.4361165960994073
Prediction:-0.09465878411423806
Prediction:-0.07546321282549368
Error:0.454736347803985
Prediction:-0.06037057026039494
Prediction:-0.0621436489828015
Prediction:-0.4556058710024478
Prediction:0.40936944760641564
Prediction:-0.0860282216

In [25]:
np.random.seed(1)

def relu(x):
    return (x > 0) * x # returns x if x > 0
                       # return 0 otherwise

def relu2deriv(output):
    return output>0 # returns 1 for input > 0
                    # return 0 otherwise

streetlights = np.array( [[ 1, 0, 1 ],
                          [ 0, 1, 1 ],
                          [ 0, 0, 1 ],
                          [ 1, 1, 1 ] ] )

walk_vs_stop = np.array([[ 1, 1, 0, 0]]).T
    
alpha = 0.2
hidden_size = 4

weights_0 = np.random.random((3,hidden_size))
weights_1 = np.random.random((hidden_size,1))

for iteration in range(20):
    for row in range(len(streetlights)):
        layer_0 = streetlights[row:row+1]
        layer_1 = relu(np.dot(layer_0,weights_0))
        layer_2 = np.dot(layer_1,weights_1)
       
        
        delta_1 = walk_vs_stop[row] - layer_2
        delta_0 = delta_1.dot(weights_1.T) * relu2deriv(layer_1) 

        weights_0 -= alpha * layer_0.T.dot(delta_0)
        weights_1 -= alpha * layer_1.T.dot(delta_1)
        
        
     
        
        



[[0.35836595]
 [1.11626144]
 [0.10669236]
 [0.85724529]]
[[0.49297419]
 [1.3005898 ]
 [0.24787683]
 [1.12489035]]
[[0.77862248]
 [1.83132305]
 [0.49535873]
 [1.68166048]]
[[4.10236737]
 [8.40229068]
 [2.3019434 ]
 [7.54628344]]
[[183.4423531 ]
 [416.49242821]
 [108.79469048]
 [371.07667819]]
[[ 9064859.34290544]
 [18623651.78351011]
 [ 5114293.38325523]
 [16755726.67609972]]
[[1.92417932e+21]
 [4.36870190e+21]
 [1.14117776e+21]
 [3.89232426e+21]]
[[1.04615572e+64]
 [2.14931518e+64]
 [5.90229484e+63]
 [1.93374200e+64]]
[[1.18307240e+193]
 [2.68607535e+193]
 [7.01647655e+192]
 [2.39317685e+193]]
[[inf]
 [inf]
 [inf]
 [inf]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 

In [19]:
range(len(streetlights))

range(0, 4)