In [6]:
import torch
import tensorflow as tf

In [3]:
x = torch.tensor([[25,2],[5,26],[3,7]])

In [4]:
x.shape

torch.Size([3, 2])

In [5]:
x[1,:]

tensor([ 5, 26])

In [7]:
x= tf.Variable([[25,2],[5,26],[3,7]])

2022-01-29 12:33:50.183133: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [8]:
tf.rank(x)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [9]:
tf.shape(x)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [10]:
x[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 26], dtype=int32)>